/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rizalfadiaalfikri;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JDesktopPane;
/**
 *
 * @author ASUS
 */
public class MenuList extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormList
     */
    public MenuList() {
        initComponents();
        this.refreshData();
    }
    
    public void refreshData(){
        DefaultTableModel tableModel = (DefaultTableModel) datatable.getModel();
        
        tableModel.setRowCount(0);
        tableModel.setColumnCount(0);
        
        tableModel.addColumn("id");
        tableModel.addColumn("Nama Barang");
        tableModel.addColumn("Nama Pengirim");
        tableModel.addColumn("Nama Penerima");
        tableModel.addColumn("Alamat");
        tableModel.addColumn("Berat");
        tableModel.addColumn("Jarak");
        tableModel.addColumn("Total Ongkir");
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\ASUS\\Documents\\NetBeansProjects\\UAS\\kurir.accdb");
            
            String sql = "SELECT * FROM kurir";
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(sql);
            
            while(result.next()) {
                String id = String.valueOf(result.getInt("ID"));
                String nama_barang = result.getString("nama_barang");
                String nama_pengirim = result.getString("nama_pengirim");
                String nama_penerima = result.getString("nama_penerima");
                String alamat = result.getString("alamat");
                String berat = String.valueOf(result.getString("berat"));
                String jarak = String.valueOf(result.getString("jarak"));
                String total_ongkir = String.valueOf(result.getString("total_ongkir"));
                
                String[] row = {id, nama_barang, nama_pengirim, nama_penerima, alamat, berat, jarak, total_ongkir};
                tableModel.addRow(row);
            }
                
        }catch (Exception e) {
            System.out.println(e);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_table = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_detail = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setClosable(true);

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        data_table.setViewportView(datatable);

        btn_tambah.setBackground(new java.awt.Color(0, 240, 0));
        btn_tambah.setText("Tambah Data");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(255, 0, 255));
        btn_refresh.setText("Refresh Data");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_detail.setBackground(new java.awt.Color(0, 255, 255));
        btn_detail.setText("Detail Data");
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 255, 0));
        btn_edit.setText("Edit Data");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 0));
        btn_delete.setText("Delete Data");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(102, 102, 255));
        btn_print.setText("Print Data");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addGap(35, 35, 35)
                        .addComponent(btn_print))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(data_table, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambah)
                            .addComponent(btn_print))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_table, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_detail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        // TODO add your handling code here:
        int row = datatable.getSelectedRow();
        String detail_id = datatable.getModel().getValueAt(row, 0).toString();
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\ASUS\\Documents\\NetBeansProjects\\UAS\\kurir.accdb");
            
            String sql = "SELECT * FROM kurir Where id = " + detail_id;
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(sql);
            
            while(result.next()) {
                String message = "";
                message += "================\n";
                message += "Detail Data\n";
                message += "================\n";
                message += "Id : " + String.valueOf(result.getInt("ID")) + "\n";
                message += "Nama Barang : " + result.getString("nama_barang") + "\n";
                message += "Nama Pengirim: " + result.getString("nama_pengirim") + "\n";
                message += "Nama Penerima : " + result.getString("nama_penerima") + "\n";
                message += "No Telp : " + result.getString("no_telp") + "\n";
                message += "Alamat : " + result.getString("alamat") + "\n";
                message += "Berat : " + String.valueOf(result.getString("berat")) + "\n";
                message += "Jarak : " + String.valueOf(result.getString("jarak")) + "\n";
                message += "Jenis Pengiriman : " + result.getString("jenis_pengiriman") + "\n";
                message += "Harga Ongkir : " + String.valueOf(result.getString("harga_ongkir")) + "\n";
                message += "Pajak : " + String.valueOf(result.getString("pajak")) + "\n";
                message += "Total Ongkir : " + String.valueOf(result.getString("total_ongkir")) + "\n";
                
                JOptionPane.showMessageDialog(null, message,"Informaton",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_detailActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        JDesktopPane desktopPane = getDesktopPane();
        MenuEdit menuEdit = new MenuEdit();
        desktopPane.add(menuEdit);
        menuEdit.setVisible(true);
        
        int row = datatable.getSelectedRow();
        menuEdit.setSelectedId(datatable.getModel().getValueAt(row, 0).toString());
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int row = datatable.getSelectedRow();
        String detail_id = datatable.getModel().getValueAt(row, 0).toString();
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\ASUS\\Documents\\NetBeansProjects\\UAS\\kurir.accdb");
            
            String sql = "Delete FROM kurir Where id = " + detail_id + ";";
            PreparedStatement statement = connection.prepareStatement(sql);
            int data = statement.executeUpdate();
            
            if (data > 0) {
                JOptionPane.showMessageDialog(null, "Delete Data Success","Information",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal","Information",JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        JDesktopPane desktopPane = getDesktopPane();
        MenuTambah menuTambah = new MenuTambah();
        desktopPane.add(menuTambah);
        menuTambah.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        this.refreshData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        try {
            boolean print = datatable.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Unable TO Print !!...");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btn_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JScrollPane data_table;
    private javax.swing.JTable datatable;
    // End of variables declaration//GEN-END:variables

}
