/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rizalfadiaalfikri;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class MenuTambah extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuTambah
     */
    public MenuTambah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_uts1 = new javax.swing.JLabel();
        txt_uts1 = new javax.swing.JTextField();
        lbl_nilai_uts1 = new javax.swing.JLabel();
        txt_nilai_uts1 = new javax.swing.JTextField();
        lbl_nama_barang = new javax.swing.JLabel();
        txt_nama_barang = new javax.swing.JTextField();
        lbl_nama_pengirim = new javax.swing.JLabel();
        txt_nama_pengirim = new javax.swing.JTextField();
        lbl_notelpn = new javax.swing.JLabel();
        txt_notelpn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        lbl_alamat = new javax.swing.JLabel();
        txt_berat = new javax.swing.JTextField();
        lbl_berat = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        lbl_jarak = new javax.swing.JLabel();
        txt_jarak = new javax.swing.JTextField();
        lbl_jenis_pengiriman = new javax.swing.JLabel();
        cmb_jenis_pengiriman = new javax.swing.JComboBox<>();
        lbl_nama_penerima = new javax.swing.JLabel();
        txt_nama_penerima = new javax.swing.JTextField();

        lb_uts1.setText("Nilai UTS");

        txt_uts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uts1ActionPerformed(evt);
            }
        });

        lbl_nilai_uts1.setText("Nilai UTS");

        setClosable(true);

        lbl_nama_barang.setText("Nama Barang");

        lbl_nama_pengirim.setText("Nama Pengirim");

        lbl_notelpn.setText("No Telpn");

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        lbl_alamat.setText("Alamat");

        lbl_berat.setText("Berat (Kg)");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        lbl_jarak.setText("Jarak (km)");

        txt_jarak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jarakActionPerformed(evt);
            }
        });

        lbl_jenis_pengiriman.setText("Jenis Pengiriman");

        cmb_jenis_pengiriman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Ekonomi", "Ekspress" }));

        lbl_nama_penerima.setText("Nama Penerima");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_jenis_pengiriman)
                            .addComponent(lbl_nama_barang)
                            .addComponent(lbl_nama_pengirim)
                            .addComponent(lbl_notelpn)
                            .addComponent(lbl_jarak)
                            .addComponent(lbl_berat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_jenis_pengiriman, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_jarak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_berat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_notelpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nama_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 29, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nama_penerima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nama_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_alamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama_barang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama_pengirim))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama_penerima))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_alamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_notelpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_notelpn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_berat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jarak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_jarak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_jenis_pengiriman)
                    .addComponent(cmb_jenis_pengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal)
                    .addComponent(btn_simpan))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_uts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uts1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uts1ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        double berat = 0;
        double jarak = 0;
        double harga_ongkir = 0;
        double pajak = 0;
        double total_ongkir = 0;
        
        berat = Float.parseFloat(txt_berat.getText());
        jarak = Float.parseFloat(txt_jarak.getText());
        
        if (cmb_jenis_pengiriman.getSelectedIndex() == 0) {
            if (jarak > 0 && jarak <= 50) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 10000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 15000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 20000;
                } else {
                    harga_ongkir = 0;
                }
            } else if (jarak >= 51 && jarak <= 100) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 15000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 20000;
                } else if (berat > 10.1 && berat <= 15) {
                    harga_ongkir = 25000;
                } else {
                    harga_ongkir = 0;
                }
            } else if (jarak >= 101 && jarak <= 200) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 20000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 25000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 30000;
                } else {
                    harga_ongkir = 0;
                }
            }  else {
                System.out.println("Jarak Melebihi Batas");
            }
        } else if (cmb_jenis_pengiriman.getSelectedIndex() == 1) {
            if (jarak > 0 && jarak <= 50) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 12000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 17000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 22000;
                } else {
                    harga_ongkir = 0;
                }
            } else if (jarak >= 51 && jarak <= 150) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 17000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 220000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 27000;
                } else {
                    harga_ongkir = 0;
                }
            } else if (jarak >= 151 && jarak <= 200) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 22000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 27000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 32000;
                } else {
                    harga_ongkir = 0;
                }
            } else {
                System.out.println("Jarak Melebihi Batas");
            }
        } else if (cmb_jenis_pengiriman.getSelectedIndex() == 2) {
            if (jarak > 0 && jarak <= 50) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 17000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 22000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 27000;
                } else {
                    harga_ongkir = 0;
                }
            } else if (jarak >= 51 && jarak <= 150) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 22000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 270000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 32000;
                } else {
                    harga_ongkir = 0;
                }
            } else if (jarak >= 151 && jarak <= 200) {
                if (berat > 0 && berat <= 5) {
                    harga_ongkir = 27000;
                } else if (berat > 5 && berat <= 10) {
                    harga_ongkir = 32000;
                } else if (berat > 10 && berat <= 15) {
                    harga_ongkir = 37000;
                } else {
                    harga_ongkir = 0;
                }
            } else {
                System.out.println("Jarak Melebihi Batas");
            }
        } else {
            System.out.println("Pilihan Tidak Tersedia");
        }
        
        pajak = harga_ongkir * 0.1;
        total_ongkir = harga_ongkir + pajak;
        
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\ASUS\\Documents\\NetBeansProjects\\UAS\\kurir.accdb");
            String sql = "insert into kurir ";
            sql += "(nama_barang, nama_pengirim, nama_penerima, alamat, no_telp, berat, jarak, ";
            sql += "jenis_pengiriman, harga_ongkir, pajak, total_ongkir)";
            sql += " values ";
            sql += "(?, ?, ?, ?, ?, ?, ?, ";
            sql += "?, ?, ?, ?)";
            System.out.println(sql);
            
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, txt_nama_barang.getText());
            statement.setString(2, txt_nama_pengirim.getText());
            statement.setString(3, txt_nama_penerima.getText());
            statement.setString(4, txt_alamat.getText());
            statement.setString(5, txt_notelpn.getText());
            statement.setString(6, String.valueOf(berat));
            statement.setString(7, String.valueOf(jarak));
            statement.setString(8, cmb_jenis_pengiriman.getSelectedItem().toString());
            statement.setString(9, String.valueOf(harga_ongkir));
            statement.setString(10, String.valueOf(pajak));
            statement.setString(11, String.valueOf(total_ongkir));
            
            
            int row = statement.executeUpdate();
            if (row > 0) {
                JOptionPane.showMessageDialog(null, "Insert Data Success","Information",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Insert Data Gagal","Information",JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            System.out.println("e");
        }
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_jarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jarakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jarakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cmb_jenis_pengiriman;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_uts1;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_berat;
    private javax.swing.JLabel lbl_jarak;
    private javax.swing.JLabel lbl_jenis_pengiriman;
    private javax.swing.JLabel lbl_nama_barang;
    private javax.swing.JLabel lbl_nama_penerima;
    private javax.swing.JLabel lbl_nama_pengirim;
    private javax.swing.JLabel lbl_nilai_uts1;
    private javax.swing.JLabel lbl_notelpn;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_jarak;
    private javax.swing.JTextField txt_nama_barang;
    private javax.swing.JTextField txt_nama_penerima;
    private javax.swing.JTextField txt_nama_pengirim;
    private javax.swing.JTextField txt_nilai_uts1;
    private javax.swing.JTextField txt_notelpn;
    private javax.swing.JTextField txt_uts1;
    // End of variables declaration//GEN-END:variables
}
