/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rizalfadiaalfikri;

/**
 *
 * @author ASUS
 */
public class Pertemuan7 extends javax.swing.JFrame {

    /**
     * Creates new form Pertemuan7
     */
    public Pertemuan7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nama = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        lbl_jenis_kelamin = new javax.swing.JLabel();
        rb_laki_laki = new javax.swing.JRadioButton();
        rb_perempuan = new javax.swing.JRadioButton();
        lbl_mata_kuliah = new javax.swing.JLabel();
        cmb_mata_kuliah = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        lbl_alamat = new javax.swing.JLabel();
        chb_pertemuan1 = new javax.swing.JCheckBox();
        lbl_absen = new javax.swing.JLabel();
        chb_pertemuan2 = new javax.swing.JCheckBox();
        chb_pertemuan3 = new javax.swing.JCheckBox();
        chb_pertemuan4 = new javax.swing.JCheckBox();
        chb_pertemuan6 = new javax.swing.JCheckBox();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        chb_pertemuan7 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_nama.setText("Nama");

        lbl_jenis_kelamin.setText("Jenis kelamin");

        rb_laki_laki.setText("Laki - Laki");
        rb_laki_laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_laki_lakiActionPerformed(evt);
            }
        });

        rb_perempuan.setText("Perempuan");
        rb_perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_perempuanActionPerformed(evt);
            }
        });

        lbl_mata_kuliah.setText("Matakuliah");

        cmb_mata_kuliah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algoritma", "Database", "Java", "Pemrograman Visual" }));

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        lbl_alamat.setText("Alamat");

        chb_pertemuan1.setText("Pertemuan 1");
        chb_pertemuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_pertemuan1ActionPerformed(evt);
            }
        });

        lbl_absen.setText("Absen");

        chb_pertemuan2.setText("Pertemuan 2");
        chb_pertemuan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_pertemuan2ActionPerformed(evt);
            }
        });

        chb_pertemuan3.setText("Pertemuan 3");
        chb_pertemuan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_pertemuan3ActionPerformed(evt);
            }
        });

        chb_pertemuan4.setText("Pertemuan 4");
        chb_pertemuan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_pertemuan4ActionPerformed(evt);
            }
        });

        chb_pertemuan6.setText("Pertemuan 5");
        chb_pertemuan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_pertemuan6ActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        chb_pertemuan7.setText("Pertemuan 6");
        chb_pertemuan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_pertemuan7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nama)
                    .addComponent(lbl_jenis_kelamin)
                    .addComponent(lbl_mata_kuliah)
                    .addComponent(lbl_alamat)
                    .addComponent(lbl_absen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rb_perempuan)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cmb_mata_kuliah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chb_pertemuan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(chb_pertemuan2)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(chb_pertemuan6)
                                .addGap(45, 45, 45)
                                .addComponent(chb_pertemuan7))
                            .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chb_pertemuan3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb_pertemuan4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_laki_laki, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_laki_laki)
                            .addComponent(rb_perempuan)
                            .addComponent(lbl_jenis_kelamin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_mata_kuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mata_kuliah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chb_pertemuan1)
                            .addComponent(chb_pertemuan2)
                            .addComponent(lbl_absen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chb_pertemuan3)
                            .addComponent(chb_pertemuan4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chb_pertemuan6)
                            .addComponent(chb_pertemuan7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nama)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_alamat)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btn_batal)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_simpan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_laki_lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_laki_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_laki_lakiActionPerformed

    private void chb_pertemuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_pertemuan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_pertemuan1ActionPerformed

    private void chb_pertemuan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_pertemuan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_pertemuan2ActionPerformed

    private void chb_pertemuan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_pertemuan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_pertemuan3ActionPerformed

    private void chb_pertemuan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_pertemuan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_pertemuan4ActionPerformed

    private void chb_pertemuan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_pertemuan6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_pertemuan6ActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalActionPerformed

    private void chb_pertemuan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_pertemuan7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_pertemuan7ActionPerformed

    private void rb_perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_perempuanActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        System.out.println("Ini dari button simpan");
    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pertemuan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pertemuan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pertemuan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pertemuan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pertemuan7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JCheckBox chb_pertemuan1;
    private javax.swing.JCheckBox chb_pertemuan2;
    private javax.swing.JCheckBox chb_pertemuan3;
    private javax.swing.JCheckBox chb_pertemuan4;
    private javax.swing.JCheckBox chb_pertemuan6;
    private javax.swing.JCheckBox chb_pertemuan7;
    private javax.swing.JComboBox<String> cmb_mata_kuliah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_absen;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_jenis_kelamin;
    private javax.swing.JLabel lbl_mata_kuliah;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JRadioButton rb_laki_laki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
